### ISSUE TITLE
postman导入失败

### ISSUE THREAD

**Issue by aochant** [eolinker/eoLinker-AMS-Lite-For-Java#4]
POST http://localhost:8080/Import/importPostMan 404 ()   
后端没实现就把功能在页面放出来了么

**Comment by dashenbibi** [comment]
最新版本4.0已经解决这个问题了，抱歉

**Comment by gaoshijun1993** [comment]
@dashenbibi 还没有推上来啊...

**Comment by eolinker** [comment]
4.0版本已经更新
